pgadmin4:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "ca-clusterissuer-external"
    hosts:
      - host: pgadmin-172-19-0-3.nip.io
        paths:
          - path: /
            pathType: Prefix
    tls:
    - hosts:
      - "*.nip.io"
      secretName: wildcard-cert-tls
