ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "ca-clusterissuer-external"
  hosts:
    - host: backstage.kuberise.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
  - hosts:
    - "*.kuberise.dev"
    secretName: wildcard-cert-tls

service:
  type: ClusterIP
  port: 7007

backstage:
  appConfig:
    db:
      connection:
        host: cnpg-database-rw.cloudnative-pg.svc.cluster.local
        port: 5432
        user: application
        existingSecret: pg-secret
        existingSecretPasswordKey: password
