persistence:
  enabled: true
service:
  type: LoadBalancer
ingress:
  tls:
  - hosts:
    - "*.nip.io"
    secretName: wildcard-cert-tls
  enabled: true
  className: nginx
  hosts:
    - host: gitea-172-19-0-3.nip.io
      paths:
        - path: /
          pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: "ca-clusterissuer-external"
